
package importservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EchoTimeService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8080/MiageWs/EchoTimeService?WSDL")
public class EchoTimeService
    extends Service
{

    private final static URL ECHOTIMESERVICE_WSDL_LOCATION;
    private final static WebServiceException ECHOTIMESERVICE_EXCEPTION;
    private final static QName ECHOTIMESERVICE_QNAME = new QName("http://webservice/", "EchoTimeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MiageWs/EchoTimeService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOTIMESERVICE_WSDL_LOCATION = url;
        ECHOTIMESERVICE_EXCEPTION = e;
    }

    public EchoTimeService() {
        super(__getWsdlLocation(), ECHOTIMESERVICE_QNAME);
    }

    public EchoTimeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOTIMESERVICE_QNAME, features);
    }

    public EchoTimeService(URL wsdlLocation) {
        super(wsdlLocation, ECHOTIMESERVICE_QNAME);
    }

    public EchoTimeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOTIMESERVICE_QNAME, features);
    }

    public EchoTimeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoTimeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EchoTime
     */
    @WebEndpoint(name = "EchoTimePort")
    public EchoTime getEchoTimePort() {
        return super.getPort(new QName("http://webservice/", "EchoTimePort"), EchoTime.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoTime
     */
    @WebEndpoint(name = "EchoTimePort")
    public EchoTime getEchoTimePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "EchoTimePort"), EchoTime.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOTIMESERVICE_EXCEPTION!= null) {
            throw ECHOTIMESERVICE_EXCEPTION;
        }
        return ECHOTIMESERVICE_WSDL_LOCATION;
    }

}
