
package importservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EchoTime", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoTime {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeByZone", targetNamespace = "http://webservice/", className = "importservice.GetTimeByZone")
    @ResponseWrapper(localName = "getTimeByZoneResponse", targetNamespace = "http://webservice/", className = "importservice.GetTimeByZoneResponse")
    @Action(input = "http://webservice/EchoTime/getTimeByZoneRequest", output = "http://webservice/EchoTime/getTimeByZoneResponse")
    public String getTimeByZone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://webservice/", className = "importservice.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://webservice/", className = "importservice.EchoResponse")
    @Action(input = "http://webservice/EchoTime/echoRequest", output = "http://webservice/EchoTime/echoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
